"""alter servicos table

Revision ID: 543c9d9a61ef
Revises: 611654e0c708
Create Date: 2025-05-21 08:17:40.148313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '543c9d9a61ef'
down_revision: Union[str, None] = '611654e0c708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicos', sa.Column('status', sa.Enum('pendente', 'concluido', name='status'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servicos', 'status')
    # ### end Alembic commands ###
